---
- name: Install dependencies
  apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
    update_cache: yes

- name: Add Docker GPG key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg
    state: present

- name: Add Docker repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_lsb.codename }} stable"
    state: present
    filename: docker

- name: Install Docker Engine
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present
    update_cache: yes

- name: Add user {{ bx_user }} to docker group
  user:
    name: "{{ bx_user }}"
    groups: docker
    append: yes

- name: Enable and start Docker service
  systemd:
    name: docker
    enabled: yes
    state: started


- name: Ensure Docker Compose plugin directory exists
  file:
    path: /usr/libexec/docker/cli-plugins
    state: directory
    mode: '0755'

- name: Download Docker Compose plugin binary
  get_url:
    url: https://github.com/docker/compose/releases/latest/download/docker-compose-linux-x86_64
    dest: /usr/libexec/docker/cli-plugins/docker-compose
    mode: '0755'

- name: Check Docker Compose version
  command: docker compose version
  register: compose_version
  changed_when: false

- name: Print Docker Compose version
  debug:
    msg: "{{ compose_version.stdout }}"
